RPG Remix/RPG Remix/Models/Ficha.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RPG_Remix.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ficha
    {
        public Ficha()
        {
            this.Propriedades = new HashSet<Propriedade>();
            this.Peculiaridades = new HashSet<Peculiaridade>();
            this.Riquezas = new HashSet<Riqueza>();
            this.ItensArmas = new HashSet<ItemArma>();
            this.Vestimenta = new HashSet<Vestimenta>();
        }
    
        public int Id { get; set; }
        public string Nome { get; set; }
        public int Idade { get; set; }
        public string Raca { get; set; }
        public string Classe { get; set; }
        public int Adre { get; set; }
        public int Ataq { get; set; }
        public int Defe { get; set; }
        public int Dest { get; set; }
        public int Forc { get; set; }
        public int Inte { get; set; }
        public int Resi { get; set; }
        public int Sabe { get; set; }
        public int Velo { get; set; }
        public int Vital { get; set; }
        public int Sort { get; set; }
        public int Suportes { get; set; }
        public int UsuarioId { get; set; }
        public int MesaId { get; set; }
        public int PtsTestes { get; set; }
        public int PtsPericias { get; set; }
        public int PtsDesvantagens { get; set; }
        public int PtsExperiencia { get; set; }
        public string DataNivel { get; set; }
    
        public virtual ICollection<Propriedade> Propriedades { get; set; }
        public virtual ICollection<Peculiaridade> Peculiaridades { get; set; }
        public virtual ICollection<Riqueza> Riquezas { get; set; }
        public virtual ICollection<ItemArma> ItensArmas { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual Mesa Mesa { get; set; }
        public virtual ICollection<Vestimenta> Vestimenta { get; set; }
    }
}

RPG Remix/RPG Remix/Controllers/FichasController.cs
using RPG_Remix.Models;
using RPG_Remix.Models.DAO;
using RPG_Remix.Models.Fachada;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace RPG_Remix.Controllers
{
    public partial class FichasController : Controller
    {
        //
        // GET: /Fichas/
        public FichaDao fichaDao = new FichaDao();
        public MesaDao mesaDao = new MesaDao();
        public PeculiaridadeDao peculiaridadeDao = new PeculiaridadeDao();
        public int usuarioId;

        public ActionResult Fichas()
        {
            usuarioId = ((Usuario)Session["usuario"]).Id;
            var fichas = fichaDao.ListarPorUsuarioId(usuarioId);
            fichas.AddRange(fichaDao.ListarDeConhecidos(usuarioId));
            return PartialView(fichas);
        }

        public ActionResult NovaFicha(string nome)
        {
            if (!string.IsNullOrEmpty(nome)) Session["nome"] = nome;
            return PartialView();
        }

        [HttpPost]
        public ActionResult NovaFicha(float Nivel, FichaCriar ficha,
            ICollection<Peculiaridade> capacidades,
            ICollection<Peculiaridade> pericias,
            ICollection<Peculiaridade> desvantagens,
            Mesa mesa)
        {
            var ptsTests = Convert.ToInt32(Nivel * 9);
            var ptsPecul = Convert.ToInt32(Nivel * 10);

            var sumT = ficha.Adre + ficha.Ataq + ficha.Defe + ficha.Dest + ficha.Forc + ficha.Inte + ficha.Resi + ficha.Sabe + ficha.Velo;

            try
            {
                if (ModelState.IsValid)
                {
                    if (sumT != ptsTests)
                    {
                        if (sumT > ptsTests) Session["alert"] = UtilsController.RenderAlert("Ops!", "Você não pode ultrapassar o número de pontos para testes atribuído pelo nível escolhido!", "warning");
                        else Session["alert"] = UtilsController.RenderAlert("Ops!", "Você deve distribuir todos os pontos para testes atribuídos pelo nível escolhido!", "warning");

                        Session["Nivel"] = Nivel;
                        Session["ptsTest"] = (sumT > ptsTests) ? "0" : sumT + "/" + ptsTests;
                        Session["ptsPecu"] = ptsPecul;
                        return PartialView();
                    }

                    var sumP = 0;

                    if (capacidades != null)
                        foreach (var c in capacidades) sumP += c.Teste;
                    if (pericias != null)
                        foreach (var p in pericias) sumP += p.Teste;
                    if (sumP > ptsPecul)
                    {
                        Session["alert"] = UtilsController.RenderAlert("Ops!", "Você não pode ultrapassar o número de pontos para peculiaridades atribuídos pelo nível escolhido!", "warning");

                        Session["Nivel"] = Nivel;
                        Session["ptsTest"] = (sumT > ptsTests) ? "0" : sumT + "/" + ptsTests;
                        Session["ptsPecu"] = ptsPecul;
                        return PartialView();
                    }

                    int mesaId;
                    if (mesaDao.Selecionar(mesa.Id) == null)
                        mesaId = mesaDao.Inserir(mesa);
                    else mesaId = mesa.Id;

                    ficha.PtsPericias = ptsPecul - sumP;

                    usuarioId = ((Usuario)Session["usuario"]).Id;
                    ficha.Ficha.UsuarioId = usuarioId;
                    ficha.Ficha.MesaId = mesaId;

                    var fichaId = fichaDao.Inserir(ficha.Ficha);


                    if (capacidades != null && capacidades.Count > 0)
                    {
                        var txt = "";
                        foreach (var c in capacidades)
                        {
                            if (c.Nome != "") c.FichaId = fichaId;
                            txt += c.Nome;
                        }
                        if (txt != "") peculiaridadeDao.InserirVarios(capacidades);
                    }

                    if (pericias != null && pericias.Count > 0)
                    {
                        var txt = "";
                        foreach (var p in pericias)
                        {
                            if (p.Nome != "") p.FichaId = fichaId;
                            txt += p.Nome;
                        }
                        if (txt != "") peculiaridadeDao.InserirVarios(pericias);
                    }

                    if (desvantagens != null && desvantagens.Count > 0)
                    {
                        var txt = "";
                        foreach (var d in desvantagens)
                        {
                            if (d.Nome != "") d.FichaId = fichaId;
                            txt += d.Nome;
                        }
                        if (txt != "") peculiaridadeDao.InserirVarios(desvantagens);
                    }

                    Session["alert"] = UtilsController.RenderAlert("Sucesso!", "A Ficha " + ficha.Nome + " foi criada com sucesso!", "success");
                    return RedirectToAction("Fichas");
                }

                Session["alert"] = UtilsController.RenderAlert("Ops!", "Alguns campos estão necessitando serem devidamente preenchidos!", "warning");

                Session["Nivel"] = Nivel;
                Session["ptsTest"] = (sumT > ptsTests) ? "0" : sumT + "/" + ptsTests;
                Session["ptsPecu"] = ptsPecul;
                return PartialView();
            }
            catch (Exception ex)
            {
                Session["alert"] = UtilsController.RenderAlert("Erro!", "Erro no servidor: " + ex.Message, "danger");

                Session["Nivel"] = Nivel;
                Session["ptsTest"] = (sumT > ptsTests) ? "0" : sumT + "/" + ptsTests;
                Session["ptsPecu"] = ptsPecul;
                return PartialView();
            }
        }
    }
}

RPG Remix/RPG Remix/Controllers/UtilsController.cs
using RPG_Remix.Models.DAO;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace RPG_Remix.Controllers
{
    public class UtilsController : Controller
    {
        public ActionResult Select_ListMesas()
        {
            var mesas = new MesaDao().Listar();
            return PartialView(mesas);
        }

        public ActionResult Select_ListMestres()
        {
            var mestres = new UsuarioDao().Listar();
            return PartialView(mestres);
        }

        [NonAction]
        public static string RenderAlert(string titulo, string mensagem, string tipo)
        {
            return "showAlert('" + titulo + "','" + mensagem + "','" + tipo + "');";
        }
    }
}

RPG Remix/RPG Remix/Views/Fichas/Fichas.cshtml
@model List<RPG_Remix.Models.Ficha>

<script>
    @Html.Raw(Session["alert"])
    @{ Session.Remove("alert"); }
</script>

<div class="scrollable">
    <div class="div-padding-top">
        <h3 class="panel panel-head">Suas Fichas</h3>
        <div class="div-table">
            <div class="panel panel-object col-md-2 col-sm-2">
                <form>
                    <h5>
                        <label for="prenome" class="hidden-xs">Novo Personagem</label>
                        <input type="text" class="form-control" id="prenome" name="nome" placeholder="nome do personagem" />
                    </h5>
                    <hr />
                    <a class="btn btn-xs btn-default btn-block" onclick="submit('GET', 'Fichas', 'NovaFicha')">CRIAR NOVA FICHA</a>
                </form>
            </div>
            @foreach (var f in @Model)
            {
                if (f.UsuarioId == ((RPG_Remix.Models.Usuario)Session["usuario"]).Id)
                {
                    <div class="panel panel-object col-md-2 col-sm-2">
                        <h5 class="no-padding">@f.Nome</h5>
                        <div class="text-uppercase col-md-12 col-sm-2 no-padding">
                            <div class="col-md-4 col-sm-4 no-padding"><h6>adre: @f.Adre</h6><h6>ataq: @f.Ataq</h6><h6>defe: @f.Defe</h6></div>
                            <div class="col-md-4 col-sm-4 no-padding"><h6>dest: @f.Dest</h6><h6>forç: @f.Forc</h6><h6>inte: @f.Inte</h6></div>
                            <div class="col-md-4 col-sm-4 no-padding"><h6>resi: @f.Resi</h6><h6>sabe: @f.Sabe</h6><h6>velo: @f.Velo</h6></div>
                        </div>
                        <hr class="hidden-xs" />
                        <div class="btn-group btn-group-justified">
                            <div class="btn btn-xs btn-primary">Ver</div>
                            <div class="btn btn-xs btn-default">Editar</div>
                        </div>
                    </div>
                }
            }
        </div>
        <h4 class="panel panel-head">Fichas de Conhecidos</h4>
        <div class="div-table">
            @foreach (var f in @Model)
            {
                if (f.UsuarioId != ((RPG_Remix.Models.Usuario)Session["usuario"]).Id)
                {
                    <div class="panel panel-object col-md-2 col-sm-2">
                        <h5>@f.Nome</h5>
                        <label>@f.Usuario.Nome</label>
                        <h6>adre: @f.Adre ataq: @f.Ataq defe: @f.Defe dest: @f.Dest forç: @f.Forc inte: @f.Inte resi: @f.Resi sabe: @f.Sabe velo: @f.Velo</h6>
                        <div class="btn-group btn-group-justified">
                            <div class="btn btn-xs btn-primary">Ver</div>
                        </div>
                    </div>
                }
            }
        </div>
    </div>
</div>
<div id="novaficha" class="modal fade mothal">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h5 class="modal-title">Nova Ficha</h5>
            </div>
            <div class="modal-body"></div>
            <div class="modal-footer">

            </div>
        </div>
    </div>
</div>

RPG Remix/RPG Remix/Views/Fichas/NovaFicha.cshtml
@model RPG_Remix.Models.Fachada.FichaCriar

<script>
    @Html.Raw(Session["alert"])
    @{ Session.Remove("alert"); }
</script>

<div class="scrollable">
    <div class="div-padding-top">
        <h3 class="panel panel-head">Nova Ficha</h3>
        <div class="panel panel-head form-inline">
            <h5>Escolha o Nível do Personagem</h5>
            <ul class="radios">
                <li class="radio" title="Dado de 6 Faces">
                    <input type="radio" name="nivel" value="6" id="6" onchange="calcPts(this.value)" />
                    <label for="6">D6</label>
                </li>
                <li class="radio" title="Dado de 8 Faces">
                    <input type="radio" name="nivel" value="8" id="8" onchange="calcPts(this.value)" />
                    <label for="8">D8</label>
                </li>
                <li class="radio" title="Dado de 10 Faces">
                    <input type="radio" name="nivel" value="10" id="10" onchange="calcPts(this.value)" />
                    <label for="10">D10</label>
                </li>
                <li class="radio" title="Dado de 12 Faces">
                    <input type="radio" name="nivel" value="12" id="12" onchange="calcPts(this.value)" />
                    <label for="12">D12</label>
                </li>
                <li class="radio" title="Dado de 14 Faces">
                    <input type="radio" name="nivel" value="14" id="14" onchange="calcPts(this.value)" />
                    <label for="14">D14</label>
                </li>
                <li class="radio" title="Dado de 16 Faces">
                    <input type="radio" name="nivel" value="16" id="16" onchange="calcPts(this.value)" />
                    <label for="16">D16</label>
                </li>
                <li class="radio" title="Dado de 18 Faces">
                    <input type="radio" name="nivel" value="18" id="18" onchange="calcPts(this.value)" />
                    <label for="18">D18</label>
                </li>
                <li class="radio" title="Dado de 20 Faces">
                    <input type="radio" name="nivel" value="20" id="20" onchange="calcPts(this.value)" />
                    <label for="20">D20</label>
                </li>
            </ul>
        </div>
        <div class="panel-body">
            <form class="">
                <input type="hidden" name="Nivel" id="Nivel" value="@Session["Nivel"]" />
                <div class="form-group-lg text-right form-inline fix-top">
                    TESTES <input type="text" id="ptsTest" disabled class="ptsAcum" value="@Session["ptsTest"]" />
                    PECULIARIDADES <input type="text" id="ptsPecs" disabled class="ptsAcum" value="@Session["ptsPecu"]" />
                </div>
                <fieldset class="panel-form col-md-12">
                    <legend class="text-whitesmoke">Dados do Personagem</legend>
                    <div class="form-group-sm col-md-6">
                        <label for="Nome" class="text-high">NOME</label> <label><span class="text-danger">*</span> @Html.ValidationMessageFor(model => model.Nome)</label>
                        @Html.TextBoxFor(model => model.Nome, new { value = @Session["nome"], placeholder = "nome do personagem", @class = "form-control" })
                    </div>
                    <div class="form-group-sm col-md-1">
                        <label for="Idade" class="text-high">IDADE</label>
                        @Html.TextBoxFor(model => model.Idade, new { placeholder = "0", type = "number", min = "0", @class = "form-control", style = "width: 60px" })
                    </div>
                    <div class="form-group-sm col-md-2">
                        <label for="Raca" class="text-high">RAÇA</label>
                        @Html.TextBoxFor(model => model.Raca, new { placeholder = "raça do personagem", @class = "form-control" })
                    </div>
                    <div class="form-group-sm col-md-2">
                        <label for="Classe" class="text-high">CLASSE</label>
                        @Html.TextBoxFor(model => model.Classe, new { placeholder = "classe do personagem", @class = "form-control" })
                    </div>
                </fieldset>
                <fieldset class="panel-form col-md-4 col-sm-4 pwidth">
                    <legend class="text-whitesmoke">Testes Físicos e Místicos</legend>
                    <div class="col-md-5">
                        <div class="form-group-sm form-inline group-test">
                            <label for="Adre" class="text-high label-test" title="Adrenalina">ADRE</label>
                            @Html.TextBoxFor(model => model.Adre, new { placeholder = "1", type = "number", min = "0", @class = "form-control input-test", style = "width: 60px", onchange = "calcPtsTest(this.id)" })
                        </div>
                        <div class="form-group-sm form-inline group-test">
                            <label for="Ataq" class="text-high label-test" title="Ataque">ATAQ</label>
                            @Html.TextBoxFor(model => model.Ataq, new { placeholder = "1", type = "number", min = "0", @class = "form-control input-test", style = "width: 60px", onchange = "calcPtsTest(this.id)" })
                        </div>
                        <div class="form-group-sm form-inline group-test">
                            <label for="Defe" class="text-high label-test" title="Defesa">DEFE</label>
                            @Html.TextBoxFor(model => model.Defe, new { placeholder = "1", type = "number", min = "0", @class = "form-control input-test", style = "width: 60px", onchange = "calcPtsTest(this.id)" })
                        </div>
                        <div class="form-group-sm form-inline group-test">
                            <label for="Dest" class="text-high label-test" title="Destreza">DEST</label>
                            @Html.TextBoxFor(model => model.Dest, new { placeholder = "1", type = "number", min = "0", @class = "form-control input-test", style = "width: 60px", onchange = "calcPtsTest(this.id)" })
                        </div>
                        <div class="form-group-sm form-inline group-test">
                            <label for="Forc" class="text-high label-test" title="Força">FORÇ</label>
                            @Html.TextBoxFor(model => model.Forc, new { placeholder = "1", type = "number", min = "0", @class = "form-control input-test", style = "width: 60px", onchange = "calcPtsTest(this.id)" })
                        </div>
                        <div class="form-group-sm form-inline group-test">
                            <label for="Inte" class="text-high label-test" title="Inteligência">INTE</label>
                            @Html.TextBoxFor(model => model.Inte, new { placeholder = "1", type = "number", min = "0", @class = "form-control input-test", style = "width: 60px", onchange = "calcPtsTest(this.id)" })
                        </div>
                        <div class="form-group-sm form-inline group-test">
                            <label for="Resi" class="text-high label-test" title="Resistência">RESI</label>
                            @Html.TextBoxFor(model => model.Resi, new { placeholder = "1", type = "number", min = "0", @class = "form-control input-test", style = "width: 60px", onchange = "calcPtsTest(this.id)" })
                        </div>
                        <div class="form-group-sm form-inline group-test">
                            <label for="Sabe" class="text-high label-test" title="Sabedoria">SABE</label>
                            @Html.TextBoxFor(model => model.Sabe, new { placeholder = "1", type = "number", min = "0", @class = "form-control input-test", style = "width: 60px", onchange = "calcPtsTest(this.id)" })
                        </div>
                        <div class="form-group-sm form-inline group-test">
                            <label for="Velo" class="text-high label-test" title="Velocidade">VELO</label>
                            @Html.TextBoxFor(model => model.Velo, new { placeholder = "1", type = "number", min = "0", @class = "form-control input-test", style = "width: 60px", onchange = "calcPtsTest(this.id)" })
                        </div>
                    </div>
                    <div class="col-md-5">
                        <div class="form-group-sm form-inline group-test">
                            <label for="Vital" class="text-high label-test" title="Vitalidade">VITAL</label>
                            @Html.TextBoxFor(model => model.Vital, new { placeholder = "1", type = "number", min = "0", @class = "form-control input-test", style = "width: 60px", onchange = "calcPtsTest(this.id)", disabled = "true" })
                        </div>
                        <div class="form-group-sm form-inline group-test">
                            <label for="Sort" class="text-high label-test" title="Sorte (clique para sortear a sorte do personagem)">SORT</label>
                            @Html.TextBoxFor(model => model.Sort, new { placeholder = "1", type = "number", min = "0", @class = "form-control input-test pin-none", style = "width: 60px", onfocus = "sort(this.id)" })
                        </div>
                    </div>
                </fieldset>
                <fieldset class="panel-form col-md-4 col-sm-4 pwidth">
                    <legend class="text-whitesmoke">Capacidades</legend>
                    <div class="btn-border">
                        <div title="Adicionar uma capacidade!" class="btn btn-default btn-block btn-pecu" onclick="maisCap()"><i class="fa fa-plus"></i></div>
                    </div>
                    <div id="caps"></div>
                </fieldset>
                <fieldset class="panel-form col-md-4 col-sm-4 pwidth">
                    <legend class="text-whitesmoke">Perícias</legend>
                    <div class="btn-border">
                        <div title="Adicionar uma perícia!" class="btn btn-default btn-block btn-pecu" onclick="maisPer()"><i class="fa fa-plus"></i></div>
                    </div>
                    <div id="pers"></div>
                </fieldset>
                <fieldset class="panel-form col-md-4 col-sm-4 pwidth">
                    <legend class="text-whitesmoke">Desvantagens</legend>
                    <div class="btn-border">
                        <div title="Adicionar uma desvantagem!" class="btn btn-default btn-block btn-pecu" onclick="maisDes()"><i class="fa fa-plus"></i></div>
                    </div>
                    <div id="desv"></div>
                </fieldset>
                <fieldset class="panel-form col-md-8 col-sm-8 pwidth">
                    <legend class="text-whitesmoke">Mesa/Mapa</legend>
                    <div class="form-group-sm col-md-6">
                        @Html.Action("Select_ListMesas", "Utils")
                        <input type="text" name="mesa.Nome" id="mesaNome" class="form-control col-md-8" placeholder="nome da mesa" style="margin-top: 14px; margin-bottom: 14px" />
                        <div class="form-inline">
                            <label for="mesa.NumeroJogadores" class="text-high">Número de Jogadores </label>
                            <input type="number" name="mesa.NumeroJogadores" id="mesaNumeroJogadores" class="form-control" style="width: 60px" min="1" value="1" />
                        </div>
                    </div>
                    <div class="form-group-sm col-md-6">
                        @Html.Action("Select_ListMestres", "Utils")
                        <textarea name="mesa.Descricao" id="mesaDescricao" class="form-control" rows="2" placeholder="descrição da mesa" style="margin-top: 14px"></textarea>
                    </div>
                    <div class="form-group-sm col-md-6 text-center">
                        <label class="btn btn-default btn-block btn-lg btn-file " onchange="loadFile(event)" style="margin-top: 80px;">
                            Adicionar Mapa<input type="file" readonly="" id="Mapa" name="Mapa" style="display: none" />
                        </label>
                    </div>
                    <div class="form-group-sm col-md-6 text-center">
                        <img id="imgMapa" style="border: 0 none transparent; margin-top: 14px; width: 330px; height: 200px" />
                    </div>
                </fieldset>
                <div class="btn btn-danger btn-submit text-left" style="position: absolute; bottom: 12px; left: 3%" onclick="loadPage('Fichas', 'Fichas')">Cancelar</div>
                <a class="btn btn-success btn-submit text-right" id="submiter" style="position: absolute; bottom: 12px; right: 3%;" onclick="submit('POST', 'Fichas', 'NovaFicha')" disabled>CRIAR ESSA FICHA</a>
            </form>
        </div>
    </div>
</div>
@section Scripts{
    @Scripts.Render("~/bundles/jqueryval")
}