RPG Remix/RPG Remix/Controllers/EntradaController.cs
using RPG_Remix.Models;
using RPG_Remix.Models.DAO;
using RPG_Remix.Models.Fachada;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace RPG_Remix.Controllers
{
    public partial class EntradaController : Controller
    {
        //
        // GET: /Entrada/

        public ActionResult Entrar()
        {
            if (Session["usuario"] != null)
                return RedirectToAction("Desktop", "Desktop");
            return View();
        }

        [HttpPost]
        public ActionResult Entrar(UsuarioEntrar u)
        {
            try
            {
                var usuario = new UsuarioDao().SelecionarPorEmail(u.Email);
                if (usuario != null)
                    if (usuario.Senha != u.Senha)
                    {
                        Session["alert"] = UtilsController.RenderAlert("Ops!", "Senha incorreta!", "warning");
                        return View();
                    }
                    else
                    {
                        Session["usuario"] = usuario;
                        return RedirectToAction("Desktop", "Desktop");
                    }
                Session["alert"] = UtilsController.RenderAlert("Vish!", "Não há cadastro com este e-mail!", "warning");
                return View();
            }
            catch (Exception ex)
            {
                Session["alert"] = UtilsController.RenderAlert("Erro!", "Erro no servidor, por favor tente novamente (agora ou mais tarde). Relatório: <br>" + ex.Message, "danger");
                return View();
            }
        }

        public ActionResult Cadastrar()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Cadastrar(UsuarioCadastrar u)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    if (string.IsNullOrEmpty(u.Descricao))
                        u.Descricao = "Não me descrevi ainda!";

                    var usuario = new UsuarioDao().SelecionarPorEmail(u.Email);
                    if (usuario != null)
                    {
                        ModelState.AddModelError("Email", "Alguém já está usando este e-mail!");
                        return View();
                    }

                    var request = Request.Files[0];

                    var mime = request.ContentType;

                    if (request != null)
                        if (mime.Equals("image/jpg")
                            || mime.Equals("image/jpeg")
                            || mime.Equals("image/png")
                            || mime.Equals("image/gif"))
                            if (request.ContentLength > 0)
                            {
                                var uPath = Server.MapPath("~/Content/Fotos");
                                string caminho = Path.Combine(@uPath, Path.GetFileName(u.Email + ".png"));

                                request.SaveAs(caminho);
                            }

                    new UsuarioDao().Inserir(u.Usuario);
                    Session["alert"] = UtilsController.RenderAlert("Parabéns!", "Você foi cadastrado com sucesso, pelo e-mail " + u.Email + "!", "success");
                    return View("Entrar");
                }
                catch (Exception ex)
                {
                    Session["alert"] = UtilsController.RenderAlert("Erro!", "Erro ao tentar cadastrar. Mas a culpa não é sua! Erro: " + ex.Message, "danger");
                    return View();
                }
            }

            Session["alert"] = UtilsController.RenderAlert("Ops!", "Preencha os campos corretamente e não deixe os obrigatórios em branco.", "warning");
            return View();
        }

        public ActionResult EmailUnico(string email)
        {
            var emails = new List<string>();
            var todos = new UsuarioDao().Listar();
            foreach (var u in todos)
                emails.Add(u.Email);

            return Json(emails.All(e => e.ToLower() != email.ToLower()), JsonRequestBehavior.AllowGet);
        }
    }
}

RPG Remix/RPG Remix/Views/Entrada/Cadastrar.cshtml
@model RPG_Remix.Models.Fachada.UsuarioCadastrar

<script>
    @Html.Raw(Session["alert"])
    @{ Session.Remove("alert"); }
</script>

<div class="text-center loading" id="loading">
    <img src="~/Content/images/ajax-loader.gif" width="30" /> Carregando...
</div>

<div class="centralizar">
    <div class="borda-cadastro">
        <div class="conteudo-cadastro terrain">
            <fieldset>
                <legend class="text-whitesmoke">CADASTRO</legend>
                @using (Html.BeginForm("Cadastrar", "Entrada", FormMethod.Post, new { enctype = "multipart/form-data" }))
                {
                    <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
                        <div class="form-group">
                            <label class="control-label" for="Nome"><span class="text-form">Nome</span> <span class="text-danger">*</span>  @Html.ValidationMessageFor(model => model.Nome)</label>
                            @Html.TextBoxFor(model => model.Nome, new { @class = "form-control", placeholder = "seu nome" })
                        </div>
                        <div class="form-group">
                            <label class="control-label" for="Email"><span class="text-form">E-mail</span> <span class="text-danger">*</span> @Html.ValidationMessageFor(model => model.Email)</label>
                            @Html.TextBoxFor(model => model.Email, new { @class = "form-control", placeholder = "exemplo@email.com" })
                        </div>
                        <div class="form-group">
                            <label class="control-label" for="Senha"><span class="text-form">Senha</span> <span class="text-danger">*</span> @Html.ValidationMessageFor(model => model.Senha)</label>
                            @Html.TextBoxFor(model => model.Senha, new { type = "password", @class = "form-control", placeholder = "*********" })
                        </div>
                        <div class="form-group">
                            <label class="control-label" for="RepSenha"><span class="text-form">Repita a Senha</span> <span class="text-danger">*</span> @Html.ValidationMessageFor(model => model.RepSenha)</label>
                            @Html.TextBoxFor(model => model.RepSenha, new { type = "password", @class = "form-control", placeholder = "*********" })
                        </div>
                    </div>
                    <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
                        <div class="form-group">
                            <label class="control-label" for="Foto"><span class="text-form">Insira uma Foto</span></label>
                            <label class="btn btn-default btn-block btn-file">
                                Clique <input type="file" readonly="" id="Foto" name="Foto" style="display: none" />
                            </label>
                        </div>
                        <div class="form-group">
                            <label class="control-label" for="DataNascimento"><span class="text-form">Data de Nascimento</span></label>
                            @Html.TextBoxFor(model => model.DataNascimento, new { @class = "form-control", placeholder = "01/01/2016" })
                        </div>
                        <div class="form-group">
                            <label class="control-label col-xs-12 col-sm-12 col-lg-12 col-md-12" for="Sexo"><span class="text-form">Sexo</span> <span class="text-danger">*</span> @Html.ValidationMessageFor(model => model.Sexo)</label>
                            <label class="radio-inline">
                                @Html.RadioButtonFor(model => model.Sexo, 'M') Masculino
                            </label>
                            <label class="radio-inline">
                                @Html.RadioButtonFor(model => model.Sexo, 'F') Feminino
                            </label>
                            <label class="radio-inline">
                                @Html.RadioButtonFor(model => model.Sexo, 'O') Outro
                            </label>
                        </div>
                        <div class="form-group">
                            @Html.TextAreaFor(model => model.Descricao, 5, 10, new { @class = "form-control", placeholder = "Descreva-se um pouco..." })
                            @Html.ValidationMessageFor(model => model.Descricao)
                        </div>
                    </div>
                    <hr />
                    <div class="text-right">
                        <button type="submit" class="btn btn-flat-no-radius btn-block btn-primary">CADASTRAR</button>
                    </div>
                    <hr />
                }
                <div class="text-left">
                    @Ajax.ActionLink("Cancelar", "Entrar", null, new AjaxOptions
                            {
                                InsertionMode = InsertionMode.Replace,
                                UpdateTargetId = "inicio-frame",
                                LoadingElementId = "loading",
                                OnBegin = "loaderOn",
                                OnSuccess = "loaderOff"
                            }, new { @class = "btn btn-sm btn-danger" })
                </div>
            </fieldset>
        </div>
    </div>
</div>
<script>
    jQuery(function ($) {
        $('#DataNascimento').mask('99/99/9999');
    });
</script>
@section Scripts{
    @Scripts.Render("~/bundles/jqueryval")
}

RPG Remix/RPG Remix/Views/Entrada/Entrar.cshtml
@model RPG_Remix.Models.Fachada.UsuarioEntrar

<script>
    @Html.Raw(Session["alert"])
    @{ Session.Remove("alert"); }
</script>

<div class="text-center loading" id="loading">
    <img src="~/Content/images/ajax-loader.gif" width="30" /> Carregando...
</div>

<div id="frame">
    <div class="borda">
        <div class="conteudo terrain">
            <fieldset>
                <legend class="text-whitesmoke">Entrada</legend>
                @using (Html.BeginForm("Entrar", "Entrada", FormMethod.Post))
                {
                    <div class="form-group">
                        <label class="control-label" for="Email"><span class="text-form">E-mail</span> <span class="text-danger">*</span> @Html.ValidationMessageFor(model => model.Email)</label>
                        @Html.TextBoxFor(model => model.Email, new { @class = "form-control", placeholder = "exemplo@email.com" })
                    </div>
                    <div class="form-group">
                        <label class="control-label" for="Senha"><span class="text-form">Senha</span> <span class="text-danger">*</span> @Html.ValidationMessageFor(model => model.Senha)</label>
                        @Html.TextBoxFor(model => model.Senha, new { type = "password", @class = "form-control", placeholder = "*********" })
                    </div>
                    <button type="submit" class="btn btn-block btn-flat-no-radius btn-primary">ENTRAR</button>
                    <hr />
                }
                <div class="text-right">
                    @Ajax.ActionLink("CADASTRE-SE", "Cadastrar", null, new AjaxOptions
                            {
                                UpdateTargetId = "inicio-frame",
                                LoadingElementId = "loading",
                                OnBegin = "loaderOn",
                                OnSuccess = "loaderOff"
                            }, new { @class = "btn btn-xs btn-block btn-success" })
                </div>
            </fieldset>
        </div>
    </div>
</div>
@section Scripts{
    @Scripts.Render("~/bundles/jqueryval")
}